project:
  type: website
  output-dir: docs

website:
  title: "Series de Tiempo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - propuestas.qmd
      - Descriptiva.qmd
    right: 
      - text: GitHub
        icon: github
        href: https://github.com/C-Mario/series
        target: _blank
    logo: images/logo2.png
  back-to-top-navigation: true
  

format:
  html:
    theme: celula.scss
    toc: true
    code-line-numbers: true
    code-copy: hover
    grid: 
      body-width: 1200px
      content-mode: slim
      margin-width: 300px
      
editor: visual

