project:
  type: website
  output-dir: docs

website:
  title: "Series de Tiempo"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      
      - text: Análisis Descriptivo
        menu:
        - DExportaciones.qmd
        - DBitcoin.qmd

      - text: Árboles Exportaciones
        menu:
        - ModelosDeArbolesSerieExportacionesdoceRetardos.qmd
        - ModelosDeArbolesSerieExportaciones.qmd

      - text: Redes Exportaciones
        menu:
        - red_exportaciones_con_12.qmd
        - red_exportaciones_con_2.qmd 
        
      - text: Árboles Bitcoin
        menu:
        - Arboles_Des_series.qmd

      - text: Redes Bitcoin
        menu:
        - red_bitcoin_con_1_bayesiano.qmd
        - red_bitcoin_con_1_grilla.qmd
        # - red_bitcoin_con_3.qmd
        
    right: 
      - text: GitHub
        icon: github
        href: https://github.com/C-Mario/series
        target: _blank
    logo: images/logo.svg
  back-to-top-navigation: true
  
  
format:
  html:
    theme: celula2.scss
    toc: true
    code-line-numbers: true
    code-copy: hover
    grid: 
      body-width: 1500px
      content-mode: slim
      margin-width: 300px
    number-sections: true
    code-block-bg: true
    code-block-border-left: "#31BAE9" 
    highlight-style: atom-one
    code-fold: false
    code-overflow: scroll
    code-tools: 
      caption: Código

    
editor: visual

